### ISSUE TITLE
BioFmtSpecimens as a Julia package

### ISSUE THREAD

**Issue by BenJWard** [BioJulia/BioFmtSpecimens#11]
I think it would be awesome if BioFmtSpecimens was made into a proper julia package, that can be loaded with `using BioFmtSpecimens` and people can then use several commands exported by the package, to easily search through the files provided by the package and then try to load them. This would also avoid repeated cloning through the Bio.jl test suite, and the tests could just require the package.

**Comment by blahah** [comment]
At the moment though it can be used in any language. Putting some Julia-specific stuff in there doesn't necessarily prevent other languages using it, but perhaps we can consider how to signal that it's a general resource while making it easy to use in Julia. Can we have the data and the package code in separate repos?

**Comment by Ward9250** [comment]
That's a really good point, and I think that's a fab idea!

**Comment by CiaranOMara** [comment]
How about moving the relevant function from https://github.com/BioJulia/BioCore.jl/blob/master/src/Testing.jl to a new julia package called BioFmtSpecimens.jl, that accesses this repository?
